language: rust
dist: trusty

# Even though this build script doesn't use sudo, we enable it in order to get
# more memory. Previously on the container infrastructure the OOM killer would
# come in and kill either the GCC processes compiling protobuf, or rustc. See
# https://github.com/travis-ci/travis-ci/issues/7427 for the source of this
# workaround.
sudo: required

cache: cargo

os:
  - linux
  - osx

rust:
  # Disable stable until cargo:rustc-env feature makes it into stable in Rust
  # 1.19 / Cargo 0.20.
  # - stable
  - nightly

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
